### ISSUE TITLE
I can't find the setup.py

### ISSUE THREAD

**Issue by rogerfedererforever** [SpyridonLaz/Coursaros#5]
please upload the setup.py, and how to use this ? use Coursaros with a course URL?

**Comment by SpyridonLaz** [comment]
Hello.


Recently, edx.org made its webpage content dynamically loaded and I need to
refactor the whole program to make it work with selenium instead of bs4.

I am actively refactoring it so in the next week i believe it will be
somewhat working again.


 how it works:
First, you will be prompted to give your edx.org credentials , then it will
scan your whole dashboard for all available courses that you have enrolled.
From there, you will be prompted to choose which courses to parse and then
it will proceed automatically.


Στις Τρί, 7 Μαρ 2023, 3:41 π.μ. ο χρήστης rogerfedererforever <
***@***.***> έγραψε:

**Comment by rogerfedererforever** [comment]
ok.waiting for you

**Comment by SpyridonLaz** [comment]
Hello. Please tell me which course are you interested exactly?

Στις Πέμ 9 Μαρ 2023, 8:18 π.μ. ο χρήστης rogerfedererforever <
***@***.***> έγραψε:

**Comment by nnbkhanh** [comment]
Hi! How are you doing? Do you still update this tool?
I can't not install setup.py (on windows & Linux same error):

```
python3 setup.py install
Traceback (most recent call last):
  File "/home/nnbkhanh/Coursaros-master/setup.py", line 8, in <module>
    with BASE_DIR.open( 'README.md', encoding='utf-8') as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
ValueError: invalid mode: 'README.md'
```

---
Then I delete the README.MD in setup.py and it show (I opened with Admin CMD, using Pip install or changing directory not work):

```
C:\Users\nnbkh\Coursaros>python3 setup.py install
running install
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-19020.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\site-packages\

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

```
---

**Comment by SpyridonLaz** [comment]
I need to fix-update setup.py, in the meanwhile, you can try running main.py directly in python console.
